var=123
a=test
b=DevOps
sample=12345
test@=123456
test-3=1234567
var1=$(hostname)
echo "the value of var =:${var}"
echo "the value of a =:${a}"
echo "the value of sample =:${sample}"
echo "the value of test@=:${test@}"
echo "the value of test-3 =:${test-3}"
echo "the value of var1 =:${var1}"